[package]
name = "tcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma = {path="./prisma"}
platform-dirs = "0.3.0"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
include_dir = "0.7.2"
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust.git", rev = "6a0119bce951c8d956542a59b2f783fc5a591fc7", features = [
  "rspc",
  "sqlite-create-many",
] }
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
tauri = { version = "1.0.5", features = ["api-all"] }
dataurl = "0.1.2"
infer = "0.9.0"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust.git", rev = "6a0119bce951c8d956542a59b2f783fc5a591fc7", features = [
  "rspc",
  "sqlite-create-many",
] }
rspc = { version = "0.0.4", features = [
  "axum",
  "tauri",
  "uuid",
  "chrono",
  "tracing",
] }
log = "0.4.17"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
