[package]
name = "tcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma = {path="./prisma"}
platform-dirs = "0.3.0"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
include_dir = "0.7.2"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.2" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.2" }
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
tauri = { version = "1.0.5", features = ["api-all"] }
