name: lint
on: 
  - push
  - pull_request

jobs:
  twidge:
    name: lint
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository 
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies 
        run: sudo apt install libdbus-1-dev pkg-config build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup2.4-dev

      - name: Lint
        run: cargo clippy -- -D warnings
