name: Lint

on:
  push:
  pull_request:

jobs:
  run-linting:
    name: Run linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
          auto_fix: true
          commit_message: 'chore(lint): fix code style issues'
          neutral_check_on_warning: true
